idf_component_register(
    SRCS
        "main.cpp" 

        

    INCLUDE_DIRS
        "."
    REQUIRES
        esp_wifi
        esp_event
        esp_netif
        esp_websocket_client
        nvs_flash
        device_config
        driver
        esp_timer
        mbedtls
        json
        servo_control
        display_status
        ui_display
        eye_animation 
        lvgl
        
        
        
    
        
        
        
)
